export let FORM_VALIDAR_PAGO = {
  tipo_formulario: 'mini',
  alertas: true,
  btn: 'Guardar',
  btnOculto: true,
  modelo: 'InfoValidarPago',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'ProgramaAcademicoId',
      label_i18n: 'programa_academico',
      placeholder_i18n: 'programa_academico',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'PeriodoId',
      label_i18n: 'periodo_id',
      placeholder_i18n: 'periodo_id',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'IdentificacionId',
      label_i18n: 'numero_identificacion',
      placeholder_i18n: 'numero_identificacion',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'PersonaId',
      label_i18n: 'aspirante',
      placeholder_i18n: 'aspirante',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoRecibo',
      label_i18n: 'tipo_recibo',
      placeholder_i18n: 'tipo_recibo',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Referencia',
      label_i18n: 'referencia',
      placeholder_i18n: 'referencia',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'ValorOrdinario',
      label_i18n: 'valor_pago',
      placeholder_i18n: 'valor_pago',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'mat-date',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'FechaOrdinaria',
      label_i18n: 'fecha_pago',
      placeholder_i18n: 'fecha_pago',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoPago',
      label_i18n: 'tipo_pago',
      placeholder_i18n: 'tipo_pago',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'EstadoRecibo',
      label_i18n: 'estado_recibo',
      placeholder_i18n: 'estado_recibo',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
  ],
}
