export let FORM_TIPO_DEPENDENCIA_DESCUENTO = {
  titulo: 'TipoDependenciaDescuento',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'TipoDependenciaDescuento',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'TipoDescuentoId',
      label_i18n: 'tipo_descuento_id',
      placeholder_i18n: 'tipo_descuento_id',
      requerido: true,
      tipo: 'TipoDescuento',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoDependenciaId',
      label_i18n: 'tipo_dependencia_id',
      placeholder_i18n: 'tipo_dependencia_id',
      requerido: true,
      tipo: 'TipoDependencia',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'PorcentajeDescuento',
      label_i18n: 'porcentaje_descuento',
      placeholder_i18n: 'porcentaje_descuento',
      requerido: true,
      tipo: 'number',
      minimo: 1,
    },
    {
      etiqueta: 'mat-date',
      claseGrid: 'col-lg-4 col-md-6 col-sm-12 col-xs-12',
      nombre: 'FechaInicio',
      label_i18n: 'fecha_inicio',
      placeholder_i18n: 'fecha_inicio',
      requerido: true,
      tipo: 'date',
    },
    {
      etiqueta: 'mat-date',
      claseGrid: 'col-lg-4 col-md-6 col-sm-12 col-xs-12',
      nombre: 'FechaFin',
      label_i18n: 'fecha_fin',
      placeholder_i18n: 'fecha_fin',
      requerido: true,
      tipo: 'date',
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-4 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
