export let FORM_VALIDACION_DESCUENTO = {
  titulo: 'ValidacionDescuento',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'ValidacionDescuento',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'SolicitudDescuentoId',
      label_i18n: 'solicitud_descuento_id',
      placeholder_i18n: 'solicitud_descuento_id',
      requerido: true,
      tipo: 'SolicitudDescuento',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoDuracionId',
      label_i18n: 'tipo_duracion_id',
      placeholder_i18n: 'tipo_duracion_id',
      requerido: true,
      tipo: 'TipoDuracion',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'ReciboMatriculaId',
      label_i18n: 'recibo_matricula_id',
      placeholder_i18n: 'recibo_matricula_id',
      requerido: true,
      tipo: 'number',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'ValorBase',
      label_i18n: 'valor_base',
      placeholder_i18n: 'valor_base',
      requerido: true,
      tipo: 'number',
      minimo: 10000,
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'ValorConDescuento',
      label_i18n: 'valor_con_descuento',
      placeholder_i18n: 'valor_con_descuento',
      requerido: true,
      tipo: 'number',
      minimo: 10000,
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Autorizado',
      label_i18n: 'autorizado',
      placeholder_i18n: 'autorizado',
      requerido: true,
      tipo: 'checkbox',
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
