export let FORM_VALOR_ATRIBUTO_LUGAR = {
  titulo: 'ValorAtributoLugar',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'ValorAtributoLugar',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Lugar',
      label_i18n: 'lugar',
      placeholder_i18n: 'lugar',
      requerido: true,
      tipo: 'Lugar',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'AtributoLugar',
      label_i18n: 'atributo_lugar',
      placeholder_i18n: 'atributo_lugar',
      requerido: true,
      tipo: 'AtributoLugar',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'Valor',
      label_i18n: 'valor',
      placeholder_i18n: 'valor',
      requerido: true,
      tipo: 'text',
    },
  ],
}
