kind: pipeline
name: campus_admin

steps:
- name: build
  image: node
  commands:
  - apt-get update -y
  - apt-get install -y zip
  - rm -rf node_modules
  - npm i
  - npm run lint
  - npm run build --build-optimizer=false
- name: publish-s3  
  image: plugins/s3
  settings:
    bucket: campus-admin
    acl: public-read
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    region: us-east-1
    source: dist/**/*
    target: /
    strip_prefix: dist
- name: notify
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram2
    to:
      from_secret: id2
    format: html
    message: >
      {{#success build.status}}
        <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">SUCCESS</a> 
        <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
      {{else}}
        <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">FAILURE</a>
        <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
      {{/success}}
    when:
    status:
    - failure
    - success
