version: '3'
networks:
 campus_virtual:

services:
  campus-admin:
     build: 
       context: .
       dockerfile: Planestic
     container_name: campus-admin
     networks:
        - campus_virtual
     labels:
        - "traefik.enable=true"
        - "traefik.http.routers.campus-admin.rule=Host(`admin.campusvirtual.udistrital.edu.co`)"
        #- "traefik.http.routers.campus-admin.middlewares=campus-admin-stripprefix"
        #- "traefik.http.middlewares.campus-admin-stripprefix.stripprefix.prefixes=/campus-admin"
        - "traefik.http.routers.campus-admin.tls=true"
        - "traefik.http.routers.campus-admin.tls.certresolver=le"
        - "traefik.http.services.campus-admin.loadbalancer.server.port=80"   
networks:
  campus_virtual:
    external: true
