export let FORM_SUBTIPO_DOCUMENTO = {
  titulo: 'SubtipoDocumento',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'SubtipoDocumento',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoDocumentoPadre',
      label_i18n: 'tipo_documento_padre',
      placeholder_i18n: 'tipo_documento_padre',
      requerido: true,
      tipo: 'TipoDocumentoPadre',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoDocumentoHijo',
      label_i18n: 'tipo_documento_hijo',
      placeholder_i18n: 'tipo_documento_hijo',
      requerido: true,
      tipo: 'TipoDocumentoHijo',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-4 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
