export let FORM_DESCUENTOS_DEPENDENCIA = {
  titulo: 'DescuentosDependencia',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'DescuentosDependencia',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
      nombre: 'Id',
      label_i18n: 'id',
      placeholder_i18n: 'id',
      requerido: true,
      tipo: 'number',
      minimo: 1,
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-9 col-md-9 col-sm-12 col-xs-12',
      nombre: 'TipoDescuentoId',
      label_i18n: 'tipo_descuento_id',
      placeholder_i18n: 'tipo_descuento_id',
      requerido: true,
      tipo: 'TipoDescuento',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
      nombre: 'PeriodoId',
      label_i18n: 'periodo_id',
      placeholder_i18n: 'periodo_id',
      requerido: true,
      tipo: 'number',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-9 col-md-9 col-sm-12 col-xs-12',
      nombre: 'DependenciaId',
      label_i18n: 'dependencia_id',
      placeholder_i18n: 'dependencia_id',
      requerido: true,
      tipo: 'ProgramaAcademico',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'PorcentajeDescuento',
      label_i18n: 'porcentaje_descuento',
      placeholder_i18n: 'porcentaje_descuento',
      requerido: true,
      tipo: 'number',
      minimo: 0,
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
