export let FORM_SOPORTE_DESCUENTO = {
  titulo: 'SoporteDescuento',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'SoporteDescuento',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'SolicitudDescuentoId',
      label_i18n: 'solicitud_descuento_id',
      placeholder_i18n: 'solicitud_descuento_id',
      requerido: true,
      tipo: 'SolicitudDescuento',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'DocumentoId',
      label_i18n: 'documento_id',
      placeholder_i18n: 'documento_id',
      requerido: true,
      tipo: 'number',
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
