export let FORM_METADATO_SUBTIPO_PRODUCCION = {
  titulo: 'MetadatoSubtipoProduccion',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'MetadatoSubtipoProduccion',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'SubtipoProduccionId',
      label_i18n: 'subtipo_produccion',
      placeholder_i18n: 'subtipo_produccion',
      requerido: true,
      tipo: 'SubtipoProduccion',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoMetadatoId',
      label_i18n: 'tipo_metadato',
      placeholder_i18n: 'tipo_metadato',
      requerido: true,
      tipo: 'TipoMetadato',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
