export let FORM_SOLICITUD_DESCUENTO = {
  titulo: 'SolicitudDescuento',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'SolicitudDescuento',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'DescuentosDependenciaId',
      label_i18n: 'descuentos_dependencia_id',
      placeholder_i18n: 'descuentos_dependencia_id',
      requerido: true,
      tipo: 'DescuentosDependencia',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'PeriodoId',
      label_i18n: 'periodo_id',
      placeholder_i18n: 'periodo_id',
      requerido: true,
      tipo: 'number',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'PersonaId',
      label_i18n: 'persona_id',
      placeholder_i18n: 'persona_id',
      requerido: true,
      tipo: 'Persona',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Estado',
      label_i18n: 'estado',
      placeholder_i18n: 'estado',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
