export let FORM_LUGAR = {
  titulo: 'Lugar',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'Lugar',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'Nombre',
      label_i18n: 'nombre',
      placeholder_i18n: 'nombre',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoLugar',
      label_i18n: 'tipo_lugar',
      placeholder_i18n: 'tipo_lugar',
      requerido: true,
      tipo: 'TipoLugar',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
