export let FORM_EXAMEN_IDIOMAS = {
  tipo_formulario: 'mini',
  alertas: true,
  btn: 'Guardar',
  btnOculto: true,
  modelo: 'InfoIdioma',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'ProgramaAcademicoId',
      label_i18n: 'programa_academico',
      placeholder_i18n: 'programa_academico',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'PeriodoId',
      label_i18n: 'periodo_id',
      placeholder_i18n: 'periodo_id',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'IdentificacionId',
      label_i18n: 'numero_identificacion',
      placeholder_i18n: 'numero_identificacion',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'PersonaId',
      label_i18n: 'aspirante',
      placeholder_i18n: 'aspirante',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Idioma',
      label_i18n: 'idioma',
      placeholder_i18n: 'idioma',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
  ],
}
