export let FORM_RELACION_CARGO = {
  titulo: 'RelacionCargo',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'RelacionCargo',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'CargoPadre',
      label_i18n: 'cargo_padre',
      placeholder_i18n: 'cargo_padre',
      requerido: true,
      tipo: 'Cargo',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'CargoHijo',
      label_i18n: 'cargo_hijo',
      placeholder_i18n: 'cargo_hijo',
      requerido: true,
      tipo: 'Cargo',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
