export let FORM_ORGANIZACION = {
  titulo: 'InfoOrganizacion',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'InfoOrganizacion',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'Nombre',
      label_i18n: 'nombre',
      placeholder_i18n: 'nombre',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoIdentificacion',
      label_i18n: 'tipo_identificacion',
      placeholder_i18n: 'tipo_identificacion',
      requerido: true,
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-10 col-xs-10',
      nombre: 'NumeroIdentificacion',
      label_i18n: 'numero_identificacion',
      placeholder_i18n: 'numero_identificacion',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoOrganizacion',
      label_i18n: 'tipo_organizacion',
      placeholder_i18n: 'tipo_organizacion',
      requerido: true,
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Pais',
      label_i18n: 'pais',
      placeholder_i18n: 'pais',
      requerido: true,
      tipo: 'Lugar',
      key: 'Nombre',
      opciones: [],
      entrelazado: true,
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
        nombre: 'Departamento',
        label_i18n: 'departamento',
        placeholder_i18n: 'departamento',
        requerido: true,
        tipo: 'Lugar',
        key: 'Nombre',
        opciones: [],
        entrelazado: true,
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
        nombre: 'Ciudad',
        label_i18n: 'ciudad',
        placeholder_i18n: 'ciudad',
        requerido: true,
        tipo: 'Lugar',
        key: 'Nombre',
        opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Direccion',
      label_i18n: 'direccion',
      placeholder_i18n: 'direccion',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-4 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Correo',
      label_i18n: 'correo_electronico',
      placeholder_i18n: 'correo_electronico',
      requerido: true,
      tipo: 'email',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-4 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Telefono',
      label_i18n: 'telefono',
      placeholder_i18n: 'telefono',
      requerido: true,
      tipo: 'text',
    },
  ],
}
