export let FORM_LUGAR_UBICACION = {
  titulo: 'LugarUbicacion',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'LugarUbicacion',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Lugar',
      label_i18n: 'lugar',
      placeholder_i18n: 'lugar',
      requerido: true,
      tipo: 'Lugar',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Direccion',
      label_i18n: 'direccion',
      placeholder_i18n: 'direccion',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'CodigoPostal',
      label_i18n: 'codigo_postal',
      placeholder_i18n: 'codigo_postal',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Estrato',
      label_i18n: 'estrato',
      placeholder_i18n: 'estrato',
      requerido: true,
      tipo: 'number',
    },
  ],
}
