export let FORM_DEPENDENCIA_PADRE = {
  titulo: 'DependenciaPadre',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'DependenciaPadre',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'PadreId',
      label_i18n: 'padre_id',
      placeholder_i18n: 'padre_id',
      requerido: true,
      tipo: 'Dependencia',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'HijaId',
      label_i18n: 'hija_id',
      placeholder_i18n: 'hija_id',
      requerido: true,
      tipo: 'Dependencia',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
