
export let FORM_ENTREVISTADOR = {
    titulo: 'Entrevistador',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Entrevistador',
    campos: [
    // {
    //     etiqueta: 'input',
    //     claseGrid: 'col-6',
    //     nombre: 'Id',
    //     label_i18n: 'id',
    //     placeholder_i18n: 'id',
    //     requerido: true,
    //     tipo: 'number',
    // },
    {
        etiqueta: 'select',
        claseGrid: 'col-8',
        nombre: 'ProgramaAcademico',
        label_i18n: 'programa_academico',
        placeholder_i18n: 'programa_academico',
        requerido: true,
        tipo: 'ProgramaAcademico',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-8',
        nombre: 'Persona',
        label_i18n: 'ente',
        placeholder_i18n: 'ente',
        requerido: true,
        tipo: 'Persona',
        key: 'NombreCompleto', // 'SegundoNombre',
        opciones: [],
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        requerido: true,
        tipo: 'checkbox',
    },
    ],
}
