export let FORM_REQUISITO_TIPO_DESCUENTO = {
  titulo: 'RequisitoTipoDescuento',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'RequisitoTipoDescuento',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
      nombre: 'Id',
      label_i18n: 'id',
      placeholder_i18n: 'id',
      requerido: true,
      tipo: 'number',
      minimo: 1,
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-9 col-md-9 col-sm-12 col-xs-12',
      nombre: 'TipoDescuentoId',
      label_i18n: 'tipo_descuento_id',
      placeholder_i18n: 'tipo_descuento_id',
      requerido: true,
      tipo: 'TipoDescuento',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'RequisitoId',
      label_i18n: 'requisito_id',
      placeholder_i18n: 'requisito_id',
      requerido: true,
      tipo: 'Requisito',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
