
export let FORM_INSCRIPCION = {
    titulo: 'Inscripcion',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Inscripcion',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'PersonaId',
        label_i18n: 'persona_id',
        placeholder_i18n: 'persona_id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'ProgramaAcademicoId',
        label_i18n: 'programa_academico_id',
        placeholder_i18n: 'programa_academico_id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'ReciboMatriculaId',
        label_i18n: 'recibo_matricula_id',
        placeholder_i18n: 'recibo_matricula_id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'ReciboInscripcionId',
        label_i18n: 'recibo_inscripcion_id',
        placeholder_i18n: 'recibo_inscripcion_id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'PeriodoId',
        label_i18n: 'periodo_id',
        placeholder_i18n: 'periodo_id',
        requerido: true,
        tipo: 'Periodo',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'EnfasisId',
        label_i18n: 'enfasis_id',
        placeholder_i18n: 'enfasis_id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'AceptaTerminos',
        label_i18n: 'acepta_terminos',
        placeholder_i18n: 'acepta_terminos',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'FechaAceptaTerminos',
        label_i18n: 'fecha_acepta_terminos',
        placeholder_i18n: 'fecha_acepta_terminos',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'EstadoInscripcionId',
        label_i18n: 'estado_inscripcion_id',
        placeholder_i18n: 'estado_inscripcion_id',
        requerido: true,
        tipo: 'EstadoInscripcion',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'TipoInscripcionId',
        label_i18n: 'tipo_inscripcion_id',
        placeholder_i18n: 'tipo_inscripcion_id',
        requerido: true,
        tipo: 'TipoInscripcion',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'PuntajeTotal',
        label_i18n: 'puntaje_total',
        placeholder_i18n: 'puntaje_total',
        requerido: true,
        tipo: 'number',
    },
    ],
}
