export let FORM_DEPENDENCIA_TIPO_DEPENDENCIA = {
  titulo: 'DependenciaTipoDependencia',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'DependenciaTipoDependencia',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'DependenciaId',
      label_i18n: 'dependencia_id',
      placeholder_i18n: 'dependencia_id',
      requerido: true,
      tipo: 'Dependencia',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoDependenciaId',
      label_i18n: 'tipo_dependencia_id',
      placeholder_i18n: 'tipo_dependencia_id',
      requerido: true,
      tipo: 'TipoDependencia',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
