
export let FORM_REQUISITO_PROGRAMA_ACADEMICO = {
    titulo: 'RequisitoProgramaAcademico',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'RequisitoProgramaAcademico',
    campos: [
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'ProgramaAcademicoId',
        label_i18n: 'programa_academico_id',
        placeholder_i18n: 'programa_academico_id',
        requerido: true,
        tipo: 'ProgramaAcademico',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'PeriodoId',
        label_i18n: 'periodo_id',
        placeholder_i18n: 'periodo_id',
        requerido: true,
        tipo: 'Periodo',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'RequisitoId',
        label_i18n: 'requisito_id',
        placeholder_i18n: 'requisito_id',
        requerido: true,
        tipo: 'Requisito',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Porcentaje',
        label_i18n: 'porcentaje',
        placeholder_i18n: 'porcentaje',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        requerido: true,
        tipo: 'checkbox',
    },
    ],
}
