
export let FORM_ENTREVISTA = {
    titulo: 'Entrevista',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Entrevista',
    campos: [
    // {
    //     etiqueta: 'input',
    //     claseGrid: 'col-6',
    //     nombre: 'Id',
    //     label_i18n: 'id',
    //     placeholder_i18n: 'id',
    //     requerido: true,
    //     tipo: 'number',
    // },
    {
        etiqueta: 'input',
        claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
        nombre: 'InscripcionId',
        label_i18n: 'admision_id',
        placeholder_i18n: 'admision_id',
        deshabilitar: 'true',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
        nombre: 'FechaEntrevista',
        label_i18n: 'fecha_entrevista',
        placeholder_i18n: 'fecha_entrevista',
        requerido: true,
        tipo: 'text',
    },
    // {
    //     etiqueta: 'input',
    //     claseGrid: 'col-6',
    //     nombre: 'Nota',
    //     label_i18n: 'nota',
    //     placeholder_i18n: 'nota',
    //     requerido: true,
    //     tipo: 'number',
    // },
    {
        etiqueta: 'select',
        claseGrid: 'col-lg-6 col-md-6 col-sm-6 col-xs-6',
        nombre: 'EstadoEntrevistaId',
        label_i18n: 'estado_entrevista',
        placeholder_i18n: 'estado_entrevista',
        requerido: true,
        tipo: 'EstadoEntrvistaId',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-lg-6 col-md-6 col-sm-6 col-xs-6',
        nombre: 'TipoEntrevistaId',
        label_i18n: 'tipo_entrevista',
        placeholder_i18n: 'tipo_entrevista',
        requerido: true,
        tipo: 'TipoEntrevistaId',
        key: 'Nombre',
        opciones: [],
    },
    ],
}
