export let FORM_ENCARGADO_EVENTO = {
  titulo: 'EncargadoEvento',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'EncargadoEvento',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'CalendarioEventoId',
      label_i18n: 'calendario_evento',
      placeholder_i18n: 'calendario_evento',
      requerido: true,
      tipo: 'CalendarioEvento',
      key: 'Descripcion',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'EncargadoId',
      label_i18n: 'encargado_id',
      placeholder_i18n: 'encargado_id',
      requerido: true,
      tipo: 'Persona',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-8 col-md-6 col-sm-12 col-xs-12',
      nombre: 'RolEncargadoId',
      label_i18n: 'rol_encargado_evento',
      placeholder_i18n: 'rol_encargado_evento',
      requerido: true,
      tipo: 'RolEncargadoEvento',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-4 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Activo',
      label_i18n: 'activo',
      placeholder_i18n: 'activo',
      requerido: true,
      tipo: 'checkbox',
    },
  ],
}
