export let FORM_EVALUACION_INSCRIPCION = {
    titulo: 'EvaluacionInscripcion',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'EvaluacionInscripcion',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'InscripcionId',
        label_i18n: 'inscripcion_id',
        placeholder_i18n: 'inscripcion_id',
        requerido: true,
        deshabilitar: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'NotaFinal',
        label_i18n: 'nota_final',
        placeholder_i18n: 'nota_final',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'RequisitoProgramaAcademicoId',
        label_i18n: 'requisito_programa_academico_id',
        placeholder_i18n: 'requisito_programa_academico_id',
        requerido: true,
        deshabilitar: true,
        tipo: 'RequisitoProgramaAcademicoId',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        requerido: true,
        deshabilitar: true,
        tipo: 'checkbox',
    },
    ],
}
